=== leonards-ar/LaborGuru_SPM/project/LaborGuru_SPM/trunk/src/main/data/sql/spm_dataset.dtd
<!ELEMENT dataset (
    tbl_customers*,
    tbl_regions*,
    tbl_areas*,
    tbl_employees*,
    tbl_permissions*,    
    tbl_menu_items*,
    tbl_operation_times*,
    tbl_stores*,
    tbl_positions*,
    tbl_profiles*,
    tbl_profiles_permissions*,
    tbl_users*,
    tbl_users_profiles*)>

<!ELEMENT tbl_areas EMPTY>
<!ATTLIST tbl_areas
    area_id CDATA #REQUIRED
    name CDATA #IMPLIED
    region_id CDATA #IMPLIED
>

<!ELEMENT tbl_customers EMPTY>
<!ATTLIST tbl_customers
    customer_id CDATA #REQUIRED
    name CDATA #IMPLIED
>

<!ELEMENT tbl_employees EMPTY>
<!ATTLIST tbl_employees
    user_id CDATA #REQUIRED
    store_id CDATA #IMPLIED
    default_position CDATA #IMPLIED
    manager CDATA #IMPLIED
    phone CDATA #IMPLIED
    phone2 CDATA #IMPLIED
    hire_date CDATA #IMPLIED
    max_hours_week CDATA #IMPLIED
    max_days_week CDATA #IMPLIED
    max_hour_day CDATA #IMPLIED
    address CDATA #IMPLIED
    address2 CDATA #IMPLIED
    city CDATA #IMPLIED
    state CDATA #IMPLIED
    zip CDATA #IMPLIED
    comments CDATA #IMPLIED
    employee_id CDATA #IMPLIED
    wage CDATA #IMPLIED
>

<!ELEMENT tbl_menu_items EMPTY>
<!ATTLIST tbl_menu_items
    menu_item_id CDATA #REQUIRED
    label_key CDATA #REQUIRED
    help_key CDATA #IMPLIED
    target CDATA #IMPLIED
    position CDATA #IMPLIED
    parent_id CDATA #IMPLIED
    permission_id CDATA #REQUIRED
>

<!ELEMENT tbl_operation_times EMPTY>
<!ATTLIST tbl_operation_times
    operation_time_id CDATA #REQUIRED
    open_hour CDATA #REQUIRED
    close_hour CDATA #REQUIRED
    day_of_week CDATA #REQUIRED
    store_id CDATA #IMPLIED
>

<!ELEMENT tbl_permissions EMPTY>
<!ATTLIST tbl_permissions
    permission_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
>

<!ELEMENT tbl_positions EMPTY>
<!ATTLIST tbl_positions
    position_id CDATA #REQUIRED
    name CDATA #IMPLIED
    store_id CDATA #IMPLIED
>

<!ELEMENT tbl_profiles EMPTY>
<!ATTLIST tbl_profiles
    profile_id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
>

<!ELEMENT tbl_profiles_permissions EMPTY>
<!ATTLIST tbl_profiles_permissions
    profile_id CDATA #REQUIRED
    permission_id CDATA #REQUIRED
>

<!ELEMENT tbl_regions EMPTY>
<!ATTLIST tbl_regions
    region_id CDATA #REQUIRED
    name CDATA #IMPLIED
    customer_id CDATA #IMPLIED
>

<!ELEMENT tbl_stores EMPTY>
<!ATTLIST tbl_stores
    store_id CDATA #REQUIRED
    name CDATA #IMPLIED
    code CDATA #IMPLIED
    first_day_of_week CDATA #IMPLIED
    area_id CDATA #IMPLIED
>

<!ELEMENT tbl_users EMPTY>
<!ATTLIST tbl_users
    user_id CDATA #REQUIRED
    username CDATA #REQUIRED
    password CDATA #IMPLIED
    status CDATA #IMPLIED
    email CDATA #IMPLIED
    name CDATA #IMPLIED
    surname CDATA #IMPLIED
    last_logon CDATA #IMPLIED
    login_count CDATA #IMPLIED
    creation_date CDATA #IMPLIED
    last_update_date CDATA #IMPLIED
>

<!ELEMENT tbl_users_profiles EMPTY>
<!ATTLIST tbl_users_profiles
    user_id CDATA #REQUIRED
    profile_id CDATA #REQUIRED
>

=== leonards-ar/LaborGuru_SPM/src/main/data/sql/seed_data_flat.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "spm_dataset.dtd">
<dataset>
  <tbl_customers customer_id="1" name="Mac Donalds"/>
  <tbl_customers customer_id="2" name="Burger King"/>
  <tbl_customers customer_id="3" name="Pizza Hut"/>
  <tbl_regions region_id="1" name="Capital Federal" customer_id="1"/>
  <tbl_regions region_id="2" name="Gran Buenos Aires" customer_id="1"/>
  <tbl_regions region_id="3" name="Cuyo" customer_id="2"/>
  <tbl_regions region_id="4" name="Mesopotamia" customer_id="2"/>
  <tbl_regions region_id="5" name="Patagonia" customer_id="3"/>
  <tbl_regions region_id="6" name="Buenos Aires" customer_id="3"/>
  <tbl_areas area_id="1" name="Monserrat" region_id="1"/>
  <tbl_areas area_id="2" name="Caballito" region_id="1"/>
  <tbl_areas area_id="3" name="Tigre" region_id="2"/>
  <tbl_areas area_id="4" name="Bahia Blanca" region_id="2"/>
  <tbl_areas area_id="5" name="San Juan" region_id="3"/>
  <tbl_areas area_id="6" name="Mendoza" region_id="3"/>
  <tbl_areas area_id="7" name="Entre Rios" region_id="4"/>
  <tbl_areas area_id="8" name="Misiones" region_id="4"/>
  <tbl_areas area_id="9" name="Chubut" region_id="5"/>
  <tbl_areas area_id="10" name="Santa Cruz" region_id="5"/>
  <tbl_areas area_id="11" name="Capital Federal" region_id="6"/>
  <tbl_areas area_id="12" name="Gran Buenos Aires" region_id="6"/>
  <tbl_permissions permission_id="1" name="FREE_ACCESS" description="Dummy permission that all profiles should have"/>
  <tbl_permissions permission_id="2" name="VIEW_EMPLOYEE" description="View and query employees of the own store"/>
  <tbl_permissions permission_id="3" name="EDIT_EMPLOYEE" description="Edit existing employees of the own store"/>
  <tbl_permissions permission_id="4" name="CREATE_EMPLOYEE" description="Create new employees in the own store"/>
  <tbl_permissions permission_id="5" name="VIEW_STORE" description="View and query stores"/>
  <tbl_permissions permission_id="6" name="EDIT_STORE" description="Edit existing stores"/>
  <tbl_permissions permission_id="7" name="CREATE_STORE" description="Create new stores"/>
  <tbl_permissions permission_id="8" name="VIEW_CUSTOMER" description="View and query customers"/>
  <tbl_permissions permission_id="9" name="EDIT_CUSTOMER" description="Edit existing customers"/>
  <tbl_permissions permission_id="10" name="CREATE_CUSTOMER" description="Create new customers"/>  
  <tbl_permissions permission_id="11" name="MANAGER_PROJECTIONS" description="Manage projections"/>  
  <tbl_permissions permission_id="12" name="EDIT_DAILY_PROJECTIONS" description="Manage daily projections"/>  
  <tbl_permissions permission_id="13" name="EDIT_HALFHOUR_PROJECTIONS" description="Manage half hour projections"/>
  <tbl_menu_items menu_item_id="1" label_key="home.menu.label" help_key="HOME_MENU_HELP" target="/home/home.action" position="0" permission_id="1"/>
  <tbl_menu_items menu_item_id="2" label_key="employee.menu.label" help_key="EMPLOYEE_MENU_HELP" target="/employee/employee_list.action" position="1" permission_id="2"/>
  <tbl_menu_items menu_item_id="3" label_key="employee.submenu.list" help_key="EMPLOYEE_LIST_HELP" target="/employee/employee_list.action" position="1" parent_id="2" permission_id="3"/>
  <tbl_menu_items menu_item_id="4" label_key="employee.submenu.create" help_key="EMPLOYEE_ADD_HELP" target="/employee/employee_add.action" position="0" parent_id="2" permission_id="4"/>
  <tbl_menu_items menu_item_id="5" label_key="store.menu.label" help_key="STORE_MENU_HELP" target="/store/store_list.action" position="2" permission_id="5"/>
  <tbl_menu_items menu_item_id="6" label_key="store.submenu.list" help_key="STORE_LIST_HELP" target="/store/store_list.action" position="1" parent_id="5" permission_id="6"/>
  <tbl_menu_items menu_item_id="7" label_key="store.submenu.create" help_key="STORE_ADD_HELP" target="/store/store_add.action" position="0" parent_id="5" permission_id="7"/>
  <tbl_menu_items menu_item_id="8" label_key="customer.menu.label" help_key="CUSTOMER_MENU_HELP" target="/customer/customer_list.action" position="3" permission_id="8"/>
  <tbl_menu_items menu_item_id="9" label_key="customer.submenu.list" help_key="CUSTOMER_LIST_HELP" target="/customer/customer_list.action" position="1" parent_id="8" permission_id="9"/>
  <tbl_menu_items menu_item_id="10" label_key="customer.submenu.create" help_key="CUSTOMER_ADD_HELP" target="/customer/customer_add.action" position="0" parent_id="8" permission_id="10"/>
  <tbl_menu_items menu_item_id="11" label_key="projection.menu.create" help_key="PROJECTION_HELP" target="/projection/daily_edit.action" position="4" permission_id="11"/>
  <tbl_menu_items menu_item_id="12" label_key="projection.submenu.daily" help_key="PROJECTION_DAILY_HELP" target="/projection/daily_edit.action" position="0" parent_id="11" permission_id="12"/>
  <tbl_menu_items menu_item_id="13" label_key="projection.submenu.halfhour" help_key="PROJECTION_HALFHOUR_HELP" target="/projection/halfhour_edit.action" position="1" parent_id="11" permission_id="13"/>
  <tbl_stores store_id="1" name="microcentro" area_id="1"/>
  <tbl_positions position_id="1" name="chef" position_index="0" store_id="1"/>
  <tbl_positions position_id="2" name="waiter" position_index="1" store_id="1"/>
  <tbl_positions position_id="3" name="cook" position_index="2" store_id="1"/>
  <tbl_positions position_id="4" name="porter" position_index="3" store_id="1"/>
  <tbl_profiles profile_id="1" name="ROLE_USER" description="Profile Desc"/>
  <tbl_profiles profile_id="2" name="ROLE_FAKE" description="Profile Desc"/>
  <tbl_profiles_permissions profile_id="1" permission_id="1"/>
  <tbl_profiles_permissions profile_id="1" permission_id="2"/>
  <tbl_profiles_permissions profile_id="1" permission_id="3"/>
  <tbl_profiles_permissions profile_id="1" permission_id="4"/>
  <tbl_profiles_permissions profile_id="1" permission_id="5"/>
  <tbl_profiles_permissions profile_id="1" permission_id="6"/>
  <tbl_profiles_permissions profile_id="1" permission_id="7"/>
  <tbl_profiles_permissions profile_id="1" permission_id="8"/>
  <tbl_profiles_permissions profile_id="1" permission_id="9"/>
  <tbl_profiles_permissions profile_id="1" permission_id="10"/>
  <tbl_profiles_permissions profile_id="1" permission_id="11"/>
  <tbl_profiles_permissions profile_id="1" permission_id="12"/>
  <tbl_profiles_permissions profile_id="1" permission_id="13"/>  
  <tbl_profiles_permissions profile_id="2" permission_id="1"/>
  <tbl_users user_id="1" username="mcapurro" password="1234" status="0" email="mcapurro@gmail.com" name="Mariano" surname="Capurro" login_count="0" creation_date="2008-07-07"/>
  <tbl_users user_id="2" username="cnunezre" password="1234" status="0" email="cnunezre@gmail.com" name="Cristian" surname="Nunez Rebolledo" login_count="0" creation_date="2008-07-07"/>
  <tbl_users user_id="3" username="fbarrera" password="1234" status="0" email="fbarrera@gmail.com" name="Federico" surname="Barrera Oro" login_count="0" creation_date="2008-07-07"/>
  <tbl_users user_id="4" username="igoris" password="1234" status="0" email="ignacio@laborguru.com" name="Ignacio" surname="Goris" login_count="0" creation_date="2008-07-07"/>
  <tbl_users user_id="5" username="fake" password="1234" status="0" email="fake@fake.com" name="Fake" surname="User" login_count="0" creation_date="2008-07-07"/>
  <tbl_users_profiles user_id="1" profile_id="1"/>
  <tbl_users_profiles user_id="2" profile_id="1"/>
  <tbl_users_profiles user_id="3" profile_id="1"/>
  <tbl_users_profiles user_id="4" profile_id="1"/>
  <tbl_users_profiles user_id="5" profile_id="2"/>
  <tbl_day_parts day_part_id="1" store_id="1" name="Breakfast" position_index="0"/>
  <tbl_day_parts day_part_id="2" store_id="1" name="Lunch" position_index="1"/>
  <tbl_day_parts day_part_id="3" store_id="1" name="Post Lunch" position_index="2"/>
  <tbl_day_parts day_part_id="4" store_id="1" name="Pre Dinner" position_index="3"/>
  <tbl_day_parts day_part_id="5" store_id="1" name="Dinner" position_index="4"/>
  <tbl_historic_sales historic_sales_id="1" date_time="2008-08-10 09:00:00" day_of_week="1" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="50" date_time="2008-08-10 09:30:00" day_of_week="1" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="100" date_time="2008-08-11 09:00:00" day_of_week="2" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="150" date_time="2008-08-11 09:30:00" day_of_week="2" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="200" date_time="2008-08-12 09:00:00" day_of_week="3" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="250" date_time="2008-08-12 09:30:00" day_of_week="3" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="300" date_time="2008-08-13 09:00:00" day_of_week="4" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="350" date_time="2008-08-13 09:30:00" day_of_week="4" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="400" date_time="2008-08-14 09:00:00" day_of_week="5" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="450" date_time="2008-08-14 09:30:00" day_of_week="5" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="500" date_time="2008-08-15 09:00:00" day_of_week="6" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="550" date_time="2008-08-15 09:30:00" day_of_week="6" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="600" date_time="2008-08-16 09:00:00" day_of_week="7" sales_value="27.8" store_id="1"/>
  <tbl_historic_sales historic_sales_id="650" date_time="2008-08-16 09:30:00" day_of_week="7" sales_value="27.8" store_id="1"/>
</dataset>
